version: '3.9'

services:
  db:
    container_name: postgres
    image: postgres
    environment:
      ALLOW_IP_RANGE: 0.0.0.0/0
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: urls
    volumes:
      - database-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"

  shortener:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    links:
      - db

volumes:
  database-data: